# Generated by Django 4.2.4 on 2023-08-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0006_alter_advert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='auction',
            field=models.BooleanField(help_text='Нажмите, если торг уместен', verbose_name='Торг'),
        ),
    ]
